openapi: 3.0.3

info:
  title: Attachment
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

components:
  schemas:
    AttachmentBase:
      description: An attachment is a file that is attached to an entity.

      externalDocs:
        url: https://datamodel.tmforum.org/en/latest/Common/EntityAttachment
      allOf:
        - $ref: "./StatusEntity.openapi.yaml#/components/schemas/StatusEntity"
        - required:
            - name
          properties:
            id:
              type: string
              format: uuid
              readOnly: true
            "@baseType":
              type: string
              default: "Attachment"
              example: "Attachment"
            status:
              type: object
              # description: Status of the attachment. This object has to be redefined in child schemas.
              # readOnly: true
            statusChangeDetails:
              readOnly: true
            name:
              description: Name of the attachment.
              type: string
              example: image.jpg
            description:
              description: Description of the attachment.
              type: string
              example: Image of the product
            mimeType:
              description: The mime type of the attachment.
              type: object
              readOnly: true
              example: image/jpeg
            size:
              description: The size of the attachment in bytes.
              type: integer
              format: int64
            uri:
              description: Uniform Resource Identifier (URI) of the attachment.
              type: string
              readOnly: true
            relatedEntity:
              description: The entities related to the attachment. This object has to be redefined in child schemas.
              type: object
            relatedParty:
              description: The parties related to the attachment.
              type: array
              items:
                $ref: "./RelatedEntity.openapi.yaml#/components/schemas/RelatedEntity"
              readOnly: true
            md5:
              description: The MD5 hash of the attachment.
              type: string
              readOnly: true
              example: 24ac5310315b1687111551f6646456d1
            sha1:
              description: The SHA1 hash of the attachment.
              type: string
              readOnly: true
              example: 92175a2c231f31ba757bc8e7620b7168707277ba
            sha256:
              description: The SHA256 hash of the attachment.
              type: string
              example: 8cf1bc0fca7f4158b8eb807be15fd7fd21bfe52d956ce3ede1511671c97dad61
      # discriminator:
      #   propertyName: "@type"

    AttachmentMonoPart:
      properties:
        status:
          enum:
            - PENDING
            - VALIDATED
            - REJECTED
          type: string
          readOnly: true
    # Attachment:
    #   allOf:
    #     - $ref: "#/components/schemas/AttachmentBase"
    #     - properties:
    #         status:
    #           enum:
    #             - PENDING
    #             - VALIDATED
    #             - REJECTED
    #           type: string
    #           readOnly: true
            # "@type":
            #   type: string
          # required:
          #   - "@type"

    SpecialisationImage:
      properties:
        mimeType:
          type: string
          enum:
            - image/jpeg
            - image/jpg
            - image/png
            - image/svg+xml
        width:
          description: The width of the image in pixels.
          type: integer
          format: int64
          example: 800
          readOnly: true
        height:
          description: The height of the image in pixels.
          type: integer
          format: int64
          example: 600
          readOnly: true
        resolution:
          description: The resolution of the image in DPI.
          type: integer
          format: int64
          example: 72
          readOnly: true
        colorDepth:
          description: The color depth of the image in bits.
          type: integer
          format: int64
          example: 24
          readOnly: true
        thumbnail:
          description: The thumbnail of the image.
          type: string
          format: base64
          readOnly: true
        thumbnailWidth:
          description: The width of the thumbnail in pixels.
          type: integer
          format: int64
          example: 80
          readOnly: true
        thumbnailHeight:
          description: The height of the thumbnail in pixels.
          type: integer
          format: int64
          example: 60
          readOnly: true
        geoLocation:
          description: The geo location of the image.
          readOnly: true
          allOf:
            - $ref: "./GeographicPoint.openapi.yaml#/components/schemas/GeographicPoint"
        exif:
          description: The EXIF data of the image.
          type: object
          readOnly: true
          additionalProperties:
            type: string
          example:
            {
              "Make": "Canon",
              "Model": "Canon EOS 5D Mark III",
              "ExposureTime": "1/60",
              "FNumber": "f/4.0",
              "ISOSpeedRatings": 3200,
              "DateTimeOriginal": "2019-12-31T23:59:59Z",
            }
    # AttachmentImage:
    #   allOf:
    #     - $ref: "#/components/schemas/Attachment"
    #     - $ref: "#/components/schemas/SpecialisationImage"
        # - properties:
        #     "@type":
        #       type: string
        #   required:
        #     - "@type"


    AttachmentFormData:
      properties:
        file:
          format: binary
          description: The file to upload
          type: string
      required:
        - file

    AttachmentMultiPart:
      # allOf:
      #   - $ref: "#/components/schemas/AttachmentBase"
      properties:
        # uploadExpectedChunks:
        #   format: int32
        #   type: integer
        #   example: 3
        #   description: The number of chunks expected to upload
        #   readOnly: true
        status:
          enum:
            - UPLOADING
            - UPLOADED
            - VALIDATED
            - REJECTED
          type: string
          readOnly: true
          description: The status of the attachment
        uploadChunks:
          readOnly: true
          uniqueItems: true
          type: array
          description: The chunks uploaded
          items:
            $ref: "#/components/schemas/Chunk"
        # "@type":
        #   type: string
          example: AttachmentMalfaconMultiPart
      required:
        - sha256
        - name
        # - size
            # - "@type"

    # AttachmentMultiPartImage:
    #   allOf:
    #     - $ref: "#/components/schemas/AttachmentMultiPart"
    #     - $ref: "#/components/schemas/SpecialisationImage"
        # - properties:
        #     "@type":
        #       type: string
        #   required:
        #     - "@type"

    Chunk:
      type: object
      required:
        - size
        - sha256
      properties:
        size:
          format: int32
          type: integer
          description: The size of the chunk
        sha256:
          type: string
          description: The SHA256 hash of the chunk
